sudo:
  required

install: "pip install jsonschema requests"

branches:
  only:
    - gh-pages

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

script: python -m unittest tests.schemata_test
